trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y curl unzip
    curl -o flutter.zip https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.1-stable.zip
    unzip flutter.zip
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter doctor
  displayName: 'Instalar Flutter'

- script: |
    flutter pub get
  displayName: 'Instalar dependencias'

- script: |
    flutter build apk --release
  displayName: 'Construir APK'

- script: |
    cp build/app/outputs/flutter-apk/app-release.apk $(Build.ArtifactStagingDirectory)/
  displayName: 'Copiar APK'

- task: PublishBuildArtifacts@1
  displayName: 'Publicar APK'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- script: |
    gh release create v$(Build.BuildId) $(Build.ArtifactStagingDirectory)/app-release.apk --repo $(Build.Repository.Uri) --title "Nueva versión" --notes "APK generado automáticamente"
  env:
    GH_TOKEN: $(GitHubToken)
  displayName: 'Subir APK a GitHub Releases'
